#!/bin/bash

install_dotfiles() {
   echo -e "\033[37;44;1m Installing Dotfiles \033[0m"

   git clone --bare https://github.com/WolfBublitz/Dotfiles.git $HOME/.dotfiles

   function dotfiles {
      /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
   }

   dotfiles config --local status.showUntrackedFiles no

   dotfiles checkout --force
}

pull_dotfiles() {
   echo -e "\033[37;44;1m Pulling Dotfiles \033[0m"

   function dotfiles {
      /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
   }

   dotfiles pull
}

push_dotfiles() {
   echo -e "\033[37;44;1m Pushing Dotfiles \033[0m"

   function dotfiles {
      /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
   }

   dotfiles push
}

add_dotfiles() {
   echo -e "\033[37;44;1m Adding Dotfiles \033[0m"

   function dotfiles {
      /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
   }

   dotfiles add $1
}

commit_dotfiles() {
   echo -e "\033[37;44;1m Committing Dotfiles \033[0m"

   function dotfiles {
      /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
   }

   dotfiles commit -a
}

declare -a common_packages=(
   bat curl git htop vim wget zsh
)

get_distro_id() {
   [ -e /etc/os-release ] && source /etc/os-release && echo "${ID:-Unknown}" && return
   [ -e /etc/lsb-release ] && source /etc/lsb-release && echo "${DISTRIB_ID:-Unknown}" && return
   [ "$(uname)" == "Darwin" ] && echo "mac" && return
}

get_distro_version() {
    [ -e /etc/os-release ] && source /etc/os-release && echo "${VERSION_ID:-Unknown}" && return
    [ -e /etc/lsb-release ] && source /etc/lsb-release && echo "${DISTRIB_RELEASE:-Unknown}" && return
    [ "$(uname)" == "Darwin" ] && echo "" && return
}

install_packages_for_arch() {
   sudo pacman -S "${common_packages[@]}"
}

install_packages_for_debian() {
   sudo apt install "${common_packages[@]}"
}

install_packages_for_fedora() {
   sudo dnf install "${common_packages[@]}" -y
}

install_packages_for_mac() {
   brew install "${common_packages[@]}"
}

install_packages_for_suse() {
   echo "Not implemented yet!"
}

install_package() {
   package_name=$1

   echo -e "\033[32;1m -> \033[34;1mInstalling $package_name\033[0m"

   case $system_info in
      manjaro) sudo pacman -S $package_name ;;
      arch) sudo pacman -S $package_name ;;
      ubuntu) sudo apt-get install -y $package_name ;;
      debian) sudo apt-get install -y $package_name ;;
      mac) brew install $package_name ;;
      fedora) sudo dnf install $package_name -y ;;
      *) echo "Unknown system!" && exit 1 ;;
   esac
}

install_oh_my_posh() {
   package_name="oh my posh"

   echo -e "\033[32;1m -> \033[34;1mInstalling $package_name\033[0m"

   mkdir -p ~/.bin

   curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/.bin
}

install_powershell() {

   package_name="PowerShell"

   echo -e "\033[32;1m -> \033[34;1mInstalling $package_name\033[0m"

   arch=$(uname -m)

   distro=$(get_distro_id)

   if [ "$distro" == "debian" ] && ([ "$arch" == "arm64" ] || [ "$arch" == "aarch64" ]); then
      install_powershell_arm
   elif [ "$distro" == "fedora" ]; then
      install_powershell_fedora
   elif [ "$distro" == "mac" ]; then
      brew install --cask powershell
   else
      bash <(curl -s https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.sh)
   fi

   echo -e "\033[32;1m -> \033[34;1mInstalling $package_name modules\033[0m"
   pwsh -NoProfile -c "Set-PSResourceRepository -Name "PSGallery" -Priority 25 -Trusted -PassThru"
   pwsh -NoProfile -c "Install-Module -Name PSReadLine -AllowClobber -Force"
   pwsh -NoProfile -c "Install-Module -Name CompletionPredictor -Force"
   pwsh -NoProfile -c "Install-Module -Name PwshSpectreConsole  -Force"
}

install_powershell_arm() {
   sudo apt-get install jq libssl1.1 libunwind8 -y

   name=$(uname -m)

   case $name in
      arm64) arch="arm";;
      aarch64) arch="arm";;
      *) echo "Unknown architecture $name!" && exit 1 ;;
   esac

   # Grab the latest tar.gz
   bits=$(getconf LONG_BIT)
   release=$(curl -sL https://api.github.com/repos/PowerShell/PowerShell/releases/latest)
   package=$(echo $release | jq -r ".assets[].browser_download_url" | grep "linux-${arch}${bits}.tar.gz")
   wget $package

   [ -e $HOME/.powershell ] && rm -rf $HOME/.powershell

   # Make folder to put powershell
   mkdir $HOME/.powershell

   # Unpack the tar.gz file
   tar -xvf "./${package##*/}" -C $HOME/.powershell

   # Make pwsh executable
   chmod +x $HOME/.powershell/pwsh

   # Create a symlink to pwsh
   [ -e $HOME/.bin/pwsh ] && rm -rf $HOME/.bin/pwsh

   ln -s $HOME/.powershell/pwsh $HOME/.bin/pwsh
}

install_powershell_fedora() {
   sudo dnf install powershell -y
}

install_fastfetch() {
   package_name="fastfetch"

   echo -e "\033[32;1m -> \033[34;1mInstalling $package_name\033[0m"

   arch=$(uname -m)

   distro=$(get_distro_id)
   distro_version=$((get_distro_version))

   if [ "$distro" == "debian" ] && [ "$distro_version" -lt 12 ]; then
      install_fastfetch_debian12
   else
      install_package fastfetch
   fi
}

install_fastfetch_debian12() {
   echo "install_fastfetch_debian12"

   arch=$(uname -m)

   if [ "$arch" == "x86_64" ]; then
      arch="amd64"
   fi

   release=$(curl -sL https://api.github.com/repos/fastfetch-cli/fastfetch/releases/latest)
   url=$(echo $release | jq -r ".assets[].browser_download_url" | grep "fastfetch-linux-$arch.zip")

   wget $url

   archive_name=${url##*/}

   [ -e $HOME/.fastfetch ] && rm -rf $HOME/.fastfetch

   unzip $archive_name -d $HOME

   rm $archive_name

   mv $HOME/${archive_name%.zip} $HOME/.fastfetch

   [ -e $HOME/.bin/fastfetch ] && rm -rf $HOME/.bin/fastfetch
   ln -s $HOME/.fastfetch/usr/bin/fastfetch $HOME/.bin/fastfetch
}

adding_package_sources() {
   system_info=$(get_distro_id)

   echo -e "\033[32;1m -> \033[31;1mAdding Package Manager\033[0m"

   case $system_info in
      fedora) adding_package_sources_fedora ;;
      *) ;;
   esac
}

adding_package_sources_fedora() {
   echo "setup Microsoft package repository"
   sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
   curl https://packages.microsoft.com/config/rhel/7/prod.repo | sudo tee /etc/yum.repos.d/microsoft.repo
   dnf makecache
}

update_package_manager() {
   system_info=$(get_distro_id)

   echo -e "\033[32;1m -> \033[31;1mUpdating Package Manager\033[0m"

   distro=$(get_distro_id)

   case $distro in
      manjaro) sudo pacman -Syu ;;
      arch) sudo pacman -Syu ;;
      ubuntu) sudo apt-get update ;;
      debian) sudo apt-get update ;;
      mac) brew update ;;
      fedora) ;;
      *) echo "Unknown system!" && exit 1 ;;
   esac
}

install_packages() {
   system_info=$(get_distro_id)
   echo -e "\033[37;44;1m Installing packages for $system_info \033[0m"

   configure_package_sources
   update_package_manager

   install_package git
   install_package bat
   install_package git
   install_package htop
   install_package lsd
   install_package vim
   install_package wget
   install_package zsh
   install_oh_my_posh
   install_powershell
   install_fastfetch
}

install_everything() {
   install_dotfiles
   install_packages
}

show_help() {
   echo -e " -id    --install-dotfiles Install dotfiles"
   echo -e " -pulld --pull-dotfiles Pull dotfiles"
   echo -e " -cd    --commit-dotfiles Commit dotfiles"
   echo -e " -pushd --push-dotfiles Push dotfiles"
   echo -e " -ip    --install-packages Install packages"
}

main() {
   case "$1" in
      -id | --install-dotfiles) install_dotfiles ;;
      -pulld | --pull-dotfiles) pull_dotfiles ;;
      -cd | --commit-dotfiles) commit_dotfiles ;;
      -ad | --add-dotfiles) add_dotfiles $2 ;;
      -pushd | --push-dotfiles) push_dotfiles ;;
      -ip | --install-packages) install_packages ;;
      -h | --help) show_help ;;
   esac
}

main "$@"
